# src/mikroabenteuer/data_seed.py
from __future__ import annotations

from typing import Any, Dict, List

from .models import MicroAdventure, ensure_unique_slugs

"""
Seed Library: Mikroabenteuer mit Carla (V2)
==========================================

Dieses Modul enthält:
1) Eine Seed-Liste aller Mikroabenteuer als MicroAdventure-Objekte
2) Eine manuelle V2-Klassifikation pro slug (Saison/Wetter/Energie/Difficulty/Safety/Mood/Alter)
3) Eine zentrale Apply-Funktion, die die Klassifikation auf die Seed-Objekte anwendet

Warum V2 als Map statt inline?
- Einheitlicher Überblick über Filter-Metadaten
- Leichtes Feintuning ohne Copy-Paste in 39 Adventure-Blöcken
- Konsistente Parameter für UI-Filter & spätere LLM-Calls
"""

# ---------------------------------------------------------------------
# V2 Klassifikation (manuell)
# ---------------------------------------------------------------------
_V2_CLASSIFICATION: Dict[str, Dict[str, Any]] = {
    # 1–5
    "blasen-parade": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne", "Bewölkt", "Wind"],
        "energy_level": "mittel",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["wild", "kreativ"],
        "safety_level": "niedrig",
    },
    "enten-zaehlerei": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["ruhig", "neugierig"],
        "safety_level": "mittel",  # Wasser
    },
    "blaetter-safari": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["neugierig", "kreativ", "ruhig"],
        "safety_level": "niedrig",
    },
    "farben-fotojagd": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["neugierig", "fokussiert"],
        "safety_level": "niedrig",
    },
    "geraeusche-bingo": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt", "Regen", "Wind"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["ruhig", "achtsam"],
        "safety_level": "niedrig",
    },
    # 6–10
    "mini-picknick": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 5.0,
        "mood_tags": ["entspannend", "ruhig"],
        "safety_level": "niedrig",
    },
    "pfuetzen-labor": {
        "season_tags": ["Frühling", "Herbst", "Winter"],
        "weather_tags": ["Regen", "Bewölkt", "Kalt"],
        "energy_level": "hoch",
        "difficulty": "mittel",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["wild", "neugierig"],
        "safety_level": "mittel",
    },
    "schatten-jagd": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne"],
        "energy_level": "hoch",
        "difficulty": "leicht",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["wild", "neugierig"],
        "safety_level": "niedrig",
    },
    "wolkenkino": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt", "Wind"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["entspannend", "kreativ", "ruhig"],
        "safety_level": "niedrig",
    },
    "spielplatz-tour": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "hoch",
        "difficulty": "mittel",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["wild", "sozial"],
        "safety_level": "mittel",
    },
    # 11–15
    "steine-mandala": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["kreativ", "fokussiert", "ruhig"],
        "safety_level": "mittel",
    },
    "balancierpfad": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "mittel",
        "difficulty": "mittel",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["fokussiert"],
        "safety_level": "mittel",
    },
    "foto-geschichte": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["kreativ", "neugierig"],
        "safety_level": "niedrig",
    },
    "duft-memo": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 5.0,
        "mood_tags": ["achtsam", "ruhig", "neugierig"],
        "safety_level": "mittel",
    },
    "bank-hopping": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "mittel",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["entspannend", "sozial"],
        "safety_level": "niedrig",
    },
    # 16–20
    "formen-schnitzeljagd": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["neugierig", "fokussiert"],
        "safety_level": "niedrig",
    },
    "mini-botaniker": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["neugierig", "achtsam", "ruhig"],
        "safety_level": "mittel",
    },
    "wind-orchester": {
        "season_tags": ["Frühling", "Herbst"],
        "weather_tags": ["Wind", "Bewölkt", "Kalt"],
        "energy_level": "mittel",
        "difficulty": "leicht",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["wild", "kreativ"],
        "safety_level": "mittel",
    },
    "spuren-suche": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt", "Regen"],
        "energy_level": "mittel",
        "difficulty": "leicht",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["neugierig", "fokussiert"],
        "safety_level": "mittel",
    },
    "muell-helden": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["sozial", "fokussiert"],
        "safety_level": "erhöht",
    },
    # 21–25
    "abend-daemmerungsrunde": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Bewölkt", "Kalt", "Sonne", "Regen"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["entspannend", "achtsam", "ruhig"],
        "safety_level": "erhöht",
    },
    "wetter-detektiv": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt", "Regen", "Wind", "Kalt", "Heiß"],
        "energy_level": "niedrig",
        "difficulty": "mittel",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["neugierig", "fokussiert"],
        "safety_level": "niedrig",
    },
    "kreide-wegekunst": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["kreativ"],
        "safety_level": "niedrig",
    },
    "mini-schatzkarte": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt", "Regen"],
        "energy_level": "mittel",
        "difficulty": "mittel",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["neugierig", "fokussiert"],
        "safety_level": "niedrig",
    },
    "stoecke-trommeln": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["kreativ", "wild"],
        "safety_level": "mittel",
    },
    "mini-bootrennen": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["ruhig", "neugierig"],
        "safety_level": "mittel",
    },
    # 26–30
    "mini-geschenke-fuer-baeume": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["kreativ", "ruhig"],
        "safety_level": "niedrig",
    },
    "morgentau-expedition": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Kalt", "Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["achtsam", "ruhig", "neugierig"],
        "safety_level": "mittel",
    },
    "regen-orchester": {
        "season_tags": ["Frühling", "Herbst"],
        "weather_tags": ["Regen", "Bewölkt", "Kalt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["achtsam", "neugierig"],
        "safety_level": "mittel",
    },
    "drachen-impro": {
        "season_tags": ["Frühling", "Herbst"],
        "weather_tags": ["Wind", "Bewölkt"],
        "energy_level": "hoch",
        "difficulty": "leicht",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["wild"],
        "safety_level": "mittel",
    },
    "schatten-theater": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["kreativ", "ruhig"],
        "safety_level": "niedrig",
    },
    "baumstamm-parcours": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "hoch",
        "difficulty": "mittel",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["wild", "fokussiert"],
        "safety_level": "mittel",
    },
    # 31+ (erweiterte Seed‑Bibliothek)
    "kaefer-detektive": {
        "season_tags": ["Frühling", "Sommer", "Herbst"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "mittel",
        "difficulty": "leicht",
        "age_min": 2.3,
        "age_max": 6.0,
        "mood_tags": ["neugierig", "fokussiert", "ruhig"],
        "safety_level": "mittel",
    },
    "sonnenblumen-zaehlung": {
        "season_tags": ["Frühling", "Sommer"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 5.0,
        "mood_tags": ["ruhig", "neugierig", "fokussiert"],
        "safety_level": "niedrig",
    },
    "frost-spaziergang": {
        "season_tags": ["Winter"],
        "weather_tags": ["Kalt", "Bewölkt", "Sonne"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.2,
        "age_max": 6.0,
        "mood_tags": ["ruhig", "achtsam"],
        "safety_level": "erhöht",
    },
    "mini-kompass-abenteuer": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "mittel",
        "difficulty": "mittel",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["neugierig", "fokussiert"],
        "safety_level": "niedrig",
    },
    "natur-farblabor": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["kreativ", "ruhig", "fokussiert"],
        "safety_level": "niedrig",
    },
    "hunde-beobachtungsrunde": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt", "Kalt"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.5,
        "age_max": 6.0,
        "mood_tags": ["sozial", "neugierig", "ruhig"],
        "safety_level": "erhöht",
    },
    "park-geschichten-bank": {
        "season_tags": ["Frühling", "Sommer", "Herbst", "Winter"],
        "weather_tags": ["Sonne", "Bewölkt", "Kalt", "Regen"],
        "energy_level": "niedrig",
        "difficulty": "leicht",
        "age_min": 2.0,
        "age_max": 6.0,
        "mood_tags": ["kreativ", "ruhig", "entspannend"],
        "safety_level": "niedrig",
    },
}


def _apply_v2_classification(adventures: List[MicroAdventure]) -> None:
    """
    Apply V2 metadata per slug before validation.
    Assumes MicroAdventure has these attributes (season_tags/weather_tags/energy_level/etc.).
    """
    for a in adventures:
        v2 = _V2_CLASSIFICATION.get(a.slug)
        if not v2:
            continue
        for key, value in v2.items():
            setattr(a, key, value)


# ---------------------------------------------------------------------
# Seed Adventures (1–39)
# ---------------------------------------------------------------------
def seed_adventures() -> List[MicroAdventure]:
    adventures: List[MicroAdventure] = [
        # 1) Seifenblasen-Parade
        MicroAdventure(
            slug="blasen-parade",
            title="Seifenblasen‑Parade",
            area="Volksgarten",
            short="Seifenblasen jagen, pusten, lachen – ein Mini‑Festival auf der Wiese.",
            duration_minutes=45,
            distance_km=1.2,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Wiese abseits vom Radweg (Volksgarten).",
            route_steps=[
                "Warm‑up: 3 kleine Blasen pusten und gemeinsam schauen.",
                "Mission: Carla fängt Blasen (mit Händen oder Finger‑Tippen).",
                "Parade: 5 Minuten gemütlich gehen, Blasen ziehen vor euch her.",
                "Bonus: Riesenblasen oder zwei auf einmal (wenn möglich).",
                "Abschluss: 1 letzte Blase + High‑Five, bevor Müdigkeit kommt.",
            ],
            preparation=["Seifenblasen einpacken.", "Kleidung: die auch klebrig werden darf."],
            packing_list=["Seifenblasenlösung + Puster", "Feuchttücher", "Wasser"],
            execution_tips=["Auf Gras pusten (weniger Rutschgefahr).", "Kurz und fröhlich beenden – nicht bis zum Kippmoment."],
            variations=["Abendsonnen‑Blasen (sehr schön).", "Blasen zählen: eins, zwei, viele."],
            toddler_benefits=["Auge‑Hand‑Koordination", "Atemkontrolle (spielerisch)", "Frustrationstoleranz (Blasen platzen)"],
            carla_tip="Wenn Carla frustriert ist: „Die Blase war schüchtern – wir probieren’s zusammen.“",
            risks=["Seifenlösung im Auge", "Rutschgefahr auf glattem Untergrund"],
            mitigations=["Auf Gras bleiben", "Wasser/Feuchttuch zum Spülen", "Keine Seifenpfützen auf Asphalt"],
            tags=["Bewegung", "Kreativ", "Ruhig"],
        ),

        # 2) Enten-Zählerei am Wasser
        MicroAdventure(
            slug="enten-zaehlerei",
            title="Enten‑Zählerei am Wasser",
            area="Volksgarten / Südpark",
            short="Beobachten, zählen, staunen – ein ruhiges Wasser‑Abenteuer mit klaren Sicherheitsregeln.",
            duration_minutes=50,
            distance_km=1.0,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Sicherer Standplatz mit Abstand zum Wasser.",
            route_steps=[
                "1 Minute leise stehen: Wasser schauen, Enten hören.",
                "Enten zählen (eins, zwei, viele – reicht).",
                "Entenbewegung nachmachen: Watscheln, Flügel strecken.",
                "Kreise im Wasser beobachten: Was macht Wellen?",
                "Abschluss: Enten winken + Hände reinigen (falls Kontakt zu Geländern).",
            ],
            preparation=["Wasser‑Regel vorher: Carla bleibt bei dir (Handkontakt möglich)."],
            packing_list=["Wasser", "Feuchttücher"],
            execution_tips=["Nicht füttern.", "Lieber kurze Beobachtungs‑Slots statt zu lange sitzen."],
            variations=["Vogel‑Farben suchen (braun, weiß, schwarz).", "Spuren‑Suche am Ufer (mit Abstand)."],
            toddler_benefits=["Fokus & Achtsamkeit", "Sprache (groß/klein, schnell/langsam)", "Selbstregulation durch ruhiges Schauen"],
            carla_tip="Sag nicht „Gefahr“, sag: „Wir bleiben hier zusammen.“",
            risks=["Sturz ins Wasser (Hauptthema)", "Rutschige Stellen am Ufer"],
            mitigations=["1‑Armlängen‑Regel + Carla innen, du außen", "Rutschige Kanten meiden"],
            tags=["Natur", "Ruhig", "Lernen"],
        ),

        # 3) Blätter-Safari
        MicroAdventure(
            slug="blaetter-safari",
            title="Blätter‑Safari",
            area="Volksgarten",
            short="5 Blätter finden, vergleichen, sortieren – Natur als Schatzkiste.",
            duration_minutes=60,
            distance_km=1.6,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Wiesenrand / Weg mit Bäumen.",
            route_steps=[
                "Mission erklären: Heute finden wir 5 verschiedene Blätter.",
                "Finde groß/klein, rund/spitz, gezackt/glatt.",
                "Mini‑Ausstellung auf einer Bank: sortieren, vergleichen.",
                "Bonus: Blätter werfen (nur kurz) oder Blatt‑Boote (ohne Wasser).",
                "Abschluss: Alles zurückgeben oder 1–2 Blätter zum Basteln mitnehmen.",
            ],
            preparation=["Bei Mundphase: nur große Blätter, kein Kleinkram."],
            packing_list=["Feuchttücher", "Wasser", "Optional: kleine Tüte für 1–2 Blätter"],
            execution_tips=["Nicht reißen – nur Bodenfunde.", "Erfolg = Finden, nicht Perfektion."],
            variations=["Herbst: Farben‑Safari", "Winter: Zapfen‑Safari statt Blätter"],
            toddler_benefits=["Kategorisieren", "Wortschatz (rau/glatt, groß/klein)", "Selbstwirksamkeit (ich finde etwas)"],
            carla_tip="Wenn Carla alles umsortiert: „Neue Version!“ – nicht korrigieren.",
            risks=["Schmutzige Hände", "Kleinteile im Mund (bei Samen/kleinen Teilen)"],
            mitigations=["Feuchttücher", "Große Funde bevorzugen"],
            tags=["Natur", "Ruhig", "Kreativ"],
        ),

        # 4) Farben-Fotojagd
        MicroAdventure(
            slug="farben-fotojagd",
            title="Farben‑Fotojagd",
            area="Volksgarten / Südpark",
            short="4 Farben – je 3 Funde: Der Park wird zum Memory‑Spiel.",
            duration_minutes=45,
            distance_km=1.4,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Weg mit abwechslungsreichen Objekten (Schilder, Bänke, Natur).",
            route_steps=[
                "4 Farben auswählen (z. B. rot, gelb, blau, grün).",
                "Je Farbe 3 Dinge finden und zeigen.",
                "Optional: 1 Foto pro Farbe (kurz, nicht dauernd).",
                "Bonus: „hell/dunkel“ Varianten finden.",
                "Abschluss: Carla wählt „Farbe des Tages“.",
            ],
            preparation=["Handy‑Regel: Fotos nur im Stehen."],
            packing_list=["Wasser", "Optional: Handy"],
            execution_tips=["Nicht korrigieren, wenn Carla kreativ ist.", "Lieber 2 Farben fertig als 4 mit Stress."],
            variations=["Indoor‑Farbenjagd bei Regen", "Formen + Farben kombinieren (Profi)"],
            toddler_benefits=["Visuelle Suche", "Sprache (Farben & Adjektive)", "Gemeinsame Aufmerksamkeit"],
            carla_tip="Wenn Carla keine Lust hat: nur 1 Farbe („Heute ist alles grün“).",
            risks=["Ablenkung durch Handy", "Stolpern beim Suchen im Laufen"],
            mitigations=["Stehenbleiben‑Regel", "Handy kurz halten"],
            tags=["Lernen", "Ruhig", "Kreativ"],
        ),

        # 5) Geräusche-Bingo
        MicroAdventure(
            slug="geraeusche-bingo",
            title="Geräusche‑Bingo",
            area="Volksgarten",
            short="Hören, benennen, nachmachen – die Welt ist voller Geräusche.",
            duration_minutes=40,
            distance_km=1.0,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Ruhiger Wegabschnitt + 1 Bank.",
            route_steps=[
                "10–20 Sekunden still sein: Was hörst du?",
                "3 Geräusche sammeln: Vogel, Wind, Schritte, Fahrrad, Wasser …",
                "Jedes Geräusch bekommt eine Bewegung (klatschen, stampfen, tippen).",
                "Mini‑Bingo: 5 Geräusche = Bingo.",
                "Abschluss: 3 tiefe Atemzüge als Spiel („Wolke wegpusten“).",
            ],
            preparation=["Erwartung klein: 3 Geräusche reichen."],
            packing_list=["Wasser"],
            execution_tips=["Nicht zu lange still sitzen – Bewegung einbauen.", "Wenn es laut ist: Geräusche vergleichen statt suchen."],
            variations=["Regen‑Bingo", "Wind‑Bingo"],
            toddler_benefits=["Auditive Aufmerksamkeit", "Sprache & Rhythmus", "Selbstregulation"],
            carla_tip="Wenn Carla unruhig wird: Geräusche‑Bingo im Gehen machen.",
            risks=["Überreizung bei lauter Umgebung"],
            mitigations=["Ruhige Spots wählen", "Kurze Slots"],
            tags=["Ruhig", "Lernen", "Achtsamkeit"],
        ),

        # 6) Mini-Picknick
        MicroAdventure(
            slug="mini-picknick",
            title="Mini‑Picknick mit Decken‑Insel",
            area="Volksgarten / Südpark",
            short="Eine Decke wird zur Insel: Pause, Snack, kurze Rituale – draußen ohne Stress.",
            duration_minutes=60,
            distance_km=0.6,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Wiese mit Abstand zu Radwegen.",
            route_steps=[
                "Decke ausbreiten: „Das ist unsere Insel.“",
                "Snack‑Slot: Carla darf 1 Sache auswählen und „servieren“.",
                "2 kurze Inselrunden (laufen) – dann wieder Pause.",
                "Mini‑Spiel: 3 Dinge zeigen (Baum, Wolke, Vogel).",
                "Abschluss: Müll‑Check + Hände sauber.",
            ],
            preparation=["Snacks kleinkind‑sicher vorbereiten (Trauben schneiden etc.)."],
            packing_list=["Decke", "Wasser", "Snackbox", "Feuchttücher"],
            execution_tips=["Besser 35 Minuten gut als 90 Minuten klebrig.", "Wenn Carla nicht sitzen will: Picknick auf 2 Minuten reduzieren."],
            variations=["Thermos‑Ritual im Winter", "Blätter‑Snack (nur anschauen) im Herbst"],
            toddler_benefits=["Selbstregulation (Pause üben)", "Rituale (Start/Ende)", "Autonomie (auswählen/helfen)"],
            carla_tip="Wenn Carla nicht sitzt: Aufgabe geben („Du bist Kellnerin“).",
            risks=["Verschlucken bei Snacks", "Sonne/Überhitzung"],
            mitigations=["Nur altersgerechte Snacks", "Schatten + Wasser + kurze Slots"],
            tags=["Ruhig", "Bonding", "Alltag"],
        ),

        # 7) Pfützen-Labor
        MicroAdventure(
            slug="pfuetzen-labor",
            title="Pfützen‑Labor: Spritz‑Physik für Anfänger",
            area="Volksgarten / Südpark",
            short="Regen wird zum Experiment: Spritzweite, Geräusch, Pfützen‑Boote (kurz & warm!).",
            duration_minutes=45,
            distance_km=1.0,
            best_time="bei Regen",
            stroller_ok=False,
            start_point="Wegabschnitt mit sicheren Pfützen (keine Straßenpfützen).",
            route_steps=[
                "Outfit‑Check: Stiefel + Regenhose.",
                "Pfütze klein → mittel → groß (skalieren).",
                "Experiment: kleines Platschen → (optional) Sprung.",
                "Blattboot auf Pfütze (nur beobachten).",
                "Abschluss: Stiefel‑Tanz auf trockenem Stück + warm werden.",
            ],
            preparation=["Ersatzsocken einpacken (Game‑Changer)."],
            packing_list=["Stiefel", "Regenhose", "Ersatzsocken", "Feuchttücher"],
            execution_tips=["Kurz halten – Auskühlung killt die Stimmung.", "Keine Straßenpfützen, kein Ölfilm."],
            variations=["Regen‑Orchester (wenn Carla nicht springen will)."],
            toddler_benefits=["Ursache/Wirkung", "Grobmotorik", "Muttraining"],
            carla_tip="Wenn Kleidung nervt: 2‑Minuten‑Version – einmal gucken, einmal platschen, fertig.",
            risks=["Rutschen", "Auskühlung", "Schmutzwasser"],
            mitigations=["Griffiger Untergrund, kein Rennen", "Kurze Dauer + warm anziehen", "Hände reinigen"],
            tags=["Regen", "Bewegung", "Lernen"],
        ),

        # 8) Schatten-Jagd
        MicroAdventure(
            slug="schatten-jagd",
            title="Schatten‑Jagd: Fang deinen Schatten!",
            area="Volksgarten",
            short="Schatten treten, rennen, posen – die billigste Magie der Welt.",
            duration_minutes=40,
            distance_km=1.2,
            best_time="sonnig",
            stroller_ok=True,
            start_point="Sonniger Weg oder Wiese mit klaren Schatten.",
            route_steps=[
                "Warm‑up: Carla tritt auf deinen Schatten – du reagierst übertrieben.",
                "Mission: 3 große Schatten finden, 3 kleine Schatten finden.",
                "Posen‑Runde: groß/klein, ein Bein, Arme hoch.",
                "Mini‑Rennen bis zur nächsten Bank (klarer Endpunkt).",
                "Abschluss: Schatten winken lassen.",
            ],
            preparation=["Sonnencreme/Cap bei starkem Licht."],
            packing_list=["Wasser", "Optional: Cap"],
            execution_tips=["Rennen nur auf übersichtlichen Strecken.", "Nicht auf Radwegen spielen."],
            variations=["Wenn bewölkt: Formen‑Schnitzeljagd statt Schatten."],
            toddler_benefits=["Raumwahrnehmung", "Körpergefühl", "Humor & Bindung"],
            carla_tip="Wenn Carla Regeln nicht mag: mach’s zum Rollenspiel („Schatten ist ein Tier“).",
            risks=["Stolpern beim Rennen", "Sonne/Hitze"],
            mitigations=["Kurze Rennstrecken, klare Endpunkte", "Schattenpausen + Wasser"],
            tags=["Bewegung", "Spaß", "Sonne"],
        ),

        # 9) Wolkenkino
        MicroAdventure(
            slug="wolkenkino",
            title="Wolkenkino & Geschichten erfinden",
            area="Südpark / Volksgarten",
            short="Langsames Schauen: Wolken werden zu Tieren, Schiffen, Geschichten.",
            duration_minutes=35,
            distance_km=0.5,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Wiese mit freiem Blick.",
            route_steps=[
                "Spot wählen (Decke optional).",
                "Eine Wolke auswählen: „Was ist das?“",
                "Ping‑Pong‑Geschichte: Carla 1 Satz, du 1 Satz.",
                "3 tiefe Atemzüge: „Wir pusten eine Wolke weg“.",
                "Abschluss: Carla wählt die Lieblingswolke.",
            ],
            preparation=["Nicht zu lange – 25–35 Minuten sind oft perfekt."],
            packing_list=["Optional: Decke", "Wasser"],
            execution_tips=["Wenn Carla nicht liegen will: Wolkenkino im Stehen + kurze Stopps."],
            variations=["Wind‑Modus: Wolkenrennen („welche ist schneller?“)"],
            toddler_benefits=["Sprache & Fantasie", "Gemeinsame Aufmerksamkeit", "Runterregulation"],
            carla_tip="Wenn Carla nur Quatsch macht: mitgehen – Fantasie ist das Ziel.",
            risks=["Sonne/Überhitzung", "Insekten (Wiese)"],
            mitigations=["Schattenpausen", "Kurze Dauer"],
            tags=["Ruhig", "Kreativ", "Achtsamkeit"],
        ),

        # 10) Spielplatz-Tour
        MicroAdventure(
            slug="spielplatz-tour",
            title="Spielplatz‑Tour mit 3 Missionen",
            area="Südpark",
            short="3 Missionen statt Endlos‑Chaos: Balance, Wiederholung, Schatz.",
            duration_minutes=70,
            distance_km=1.8,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Spielplatz‑Eingang (Südpark).",
            route_steps=[
                "Mission 1: Balance – 5 Schritte über etwas Balancierbares.",
                "Mission 2: Wiederholung – 3× rutschen oder 3× schaukeln.",
                "Mission 3: Schatz – Carla findet einen „Schatz“ vom Boden und zeigt ihn.",
                "Trinkpause.",
                "Abschlussfrage: „Was war am besten?“",
            ],
            preparation=["Vorab ankündigen: Nach Mission 3 gehen wir (Transitions)."],
            packing_list=["Wasser", "Feuchttücher", "Optional: kleiner Snack"],
            execution_tips=["Missionen kurz halten, Pausen einbauen.", "Bei Nässe Geräte prüfen oder Missionen anpassen."],
            variations=["Weg‑Missionen statt Spielplatz, wenn Carla nicht hin will."],
            toddler_benefits=["Grobmotorik", "Risikokompetenz", "Sozialkompetenz (warten/teilen)"],
            carla_tip="Bei ‚ich will nicht weg‘: Countdown + Abschiedsritual („Spielplatz winken“).",
            risks=["Sturz", "Sand im Auge", "Konflikte mit anderen Kindern"],
            mitigations=["Tempo reduzieren, klare Sätze", "Wasser/Feuchttuch", "Praktisch moderieren („du zuerst, dann …“)"],
            tags=["Bewegung", "Sozial", "Spielplatz"],
        ),

        # 11) Stein-Mandala
        MicroAdventure(
            slug="steine-mandala",
            title="Stein‑Mandala: Muster legen wie kleine Künstler",
            area="Volksgarten / Südpark",
            short="Kiesel sortieren, Muster legen, umsortieren – leises Konzentrationsabenteuer.",
            duration_minutes=50,
            distance_km=0.8,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Wiesenrand mit Kieseln (ohne sensible Beete).",
            route_steps=[
                "5–10 Steine sammeln (groß genug).",
                "Muster legen: Linie/Kreis/Schnecke.",
                "Wechselspiel: du legst, Carla legt.",
                "Umsortieren ist erlaubt – neue Version feiern.",
                "Abschluss: Foto optional, dann Steine zurück.",
            ],
            preparation=["Bei Mundphase: lieber Blätter/Zapfen statt Steine."],
            packing_list=["Feuchttücher", "Optional: kleines Tuch als Atelier"],
            execution_tips=["Steine bleiben am Boden.", "Wenn geworfen wird: Spiel wechseln."],
            variations=["Herbst: Blätter‑Mandala", "Winter: Stöcke auf Schnee (kurz)"],
            toddler_benefits=["Feinmotorik", "Planung & Kognition", "Frustrationstoleranz"],
            carla_tip="Wenn Carla alles zerstört: „Oh! Remix!“ – nicht korrigieren.",
            risks=["Verschlucken (kleine Steine)", "Werfen"],
            mitigations=["Nur große Steine", "Regel + sofortiger Wechsel bei Werfen"],
            tags=["Ruhig", "Kreativ", "Feinmotorik"],
        ),

        # 12) Balancier-Pfad
        MicroAdventure(
            slug="balancierpfad",
            title="Balancier‑Pfad: Bordsteine, Wurzeln, Linien",
            area="Volksgarten",
            short="Mount‑Everest‑Gefühl auf 5 cm Höhe: Balance als Gehirntraining.",
            duration_minutes=45,
            distance_km=1.5,
            best_time="vormittags",
            stroller_ok=False,
            start_point="Ruhiger Weg mit Linie/Bordkante (nicht nahe Straße).",
            route_steps=[
                "Level 1: 3× über eine Linie laufen (du gehst daneben).",
                "Level 2: 5–10 Schritte über unebenes Terrain (Wurzeln).",
                "Mini‑Challenge: bis zur Bank (kurzer Endpunkt).",
                "Reset: 30 Sekunden „Katze dehnen“.",
                "Wiederholen, wenn Carla will.",
            ],
            preparation=["Schuhe mit Grip.", "Bei Nässe lieber auslassen."],
            packing_list=["Wasser"],
            execution_tips=["Kurze Etappen, viele kleine Erfolge.", "Stopp‑Regel üben."],
            variations=["Indoor: Tape‑Linie im Flur (Schlechtwetter)."],
            toddler_benefits=["Vestibulärsystem (Gleichgewicht)", "Propriozeption", "Selbstvertrauen"],
            carla_tip="Wenn Carla nicht will: du balancierst, Carla ist Punkte‑Richterin.",
            risks=["Sturz", "Rutschgefahr bei Nässe"],
            mitigations=["Niedrige Elemente, Handkontakt", "Bei Nässe Spiel wechseln"],
            tags=["Bewegung", "Fokus", "Motorik"],
        ),

        # 13) Mini-Foto-Geschichte
        MicroAdventure(
            slug="foto-geschichte",
            title="Mini‑Foto‑Geschichte: 6 Bilder, 1 Abenteuer",
            area="Volksgarten / Südpark",
            short="6 Stationen, 6 Fotos – aus einem Spaziergang wird eine Erzählung.",
            duration_minutes=55,
            distance_km=1.3,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Startpunkt mit 5 nahen Landmarken (Bank/Baum/Wiese).",
            route_steps=[
                "6 sehr nahe Stationen wählen (Start → Ziel).",
                "An jeder Station 1 Foto (Carla darf 2–3 drücken).",
                "Mini‑Ritual: „Klick – geschafft!“",
                "Zu Hause anschauen: Carla erzählt (Frage: „Und dann?“).",
            ],
            preparation=["Foto‑Tokens: Carla bekommt z. B. 3 Foto‑Drück‑Chancen."],
            packing_list=["Optional: Handy", "Wasser"],
            execution_tips=["Handy zwischen Stationen weg.", "Keine fremden Personen/Kinder erkennbar fotografieren."],
            variations=["3‑Foto‑Story statt 6", "Indoor‑Story bei Regen"],
            toddler_benefits=["Narratives Denken", "Gedächtnisabruf", "Sprache"],
            carla_tip="Beste Frage: „Und dann?“ (statt „Was ist das?“).",
            risks=["Ablenkung durch Handy"],
            mitigations=["Fotos nur im Stehen, nicht beim Laufen"],
            tags=["Kreativ", "Sprache", "Ruhig"],
        ),

        # 14) Duft-Memo
        MicroAdventure(
            slug="duft-memo",
            title="Duft‑Memo: Riechen wie ein Spürhund",
            area="Volksgarten",
            short="Gras, Erde, Rinde – 4 Düfte reichen für ein überraschend intensives Abenteuer.",
            duration_minutes=35,
            distance_km=0.9,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Weg mit Wiese + Bäumen (ruhig).",
            route_steps=[
                "Regel: Nur riechen, nicht essen, nicht ins Auge fassen.",
                "4 Stationen: Gras, Erde, Rinde, (optional) Blüte.",
                "Memo: Carla riecht, du rätst (Gras oder Erde?).",
                "Abschluss: Hände reinigen, 1 Lieblingsduft benennen.",
            ],
            preparation=["Bei Allergie/Empfindlichkeit: kurz halten, Blüten optional."],
            packing_list=["Feuchttücher", "Wasser"],
            execution_tips=["Nur bekannte, harmlose Dinge riechen.", "Wenn Carla unruhig wird: in Bewegung weiterspielen."],
            variations=["Fühl‑Memo (glatt/rau/weich)"],
            toddler_benefits=["Sensorik", "Sprache (Adjektive)", "Achtsamkeit"],
            carla_tip="Wenn Carla überall „Pups“ riecht: nicht korrigieren – Humor nutzen.",
            risks=["Allergie/Empfindlichkeit", "Hände im Gesicht"],
            mitigations=["Kurz halten, Hände reinigen", "Blüten nur aus Distanz"],
            tags=["Achtsamkeit", "Ruhig", "Natur"],
        ),

        # 15) Bank-Hopping
        MicroAdventure(
            slug="bank-hopping",
            title="Bank‑Hopping: 10 Bänke, 10 Mini‑Spiele",
            area="Volksgarten / Südpark",
            short="Bänke als Checkpoints: kurze Spiele + klare Übergänge statt Endloslaufen.",
            duration_minutes=55,
            distance_km=2.0,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Rundweg mit mehreren Bänken (4 reichen).",
            route_steps=[
                "Route wählen: 4–10 Bänke (realistisch).",
                "Pro Bank 1 Mini‑Spiel (Tierpose, zählen, winken, Snack).",
                "Abschlussbank: „Was war die beste Bank?“",
            ],
            preparation=["Vorab Limit setzen (z. B. 4 Bänke)."],
            packing_list=["Wasser", "Optional: Snack"],
            execution_tips=["Bank nah am Radweg? Lieber weiter.", "Nicht zu viel Stationen – sonst Endlosmodus."],
            variations=["Unterstände‑Hopping bei Regen"],
            toddler_benefits=["Transitionskompetenz", "Strukturgefühl", "Autonomie (Auswahl)"],
            carla_tip="Wenn Carla nicht weiterwill: U‑Boot‑Story („Wir tauchen zur nächsten Bank auf“).",
            risks=["Bank nahe Radweg", "Zu lange sitzen im Winter"],
            mitigations=["Ruhige Bänke wählen", "Im Winter Bank nur als kurzer Checkpoint"],
            tags=["Alltag", "Ruhig", "Sozial"],
        ),

        # 16) Formen-Schnitzeljagd
        MicroAdventure(
            slug="formen-schnitzeljagd",
            title="Formen‑Schnitzeljagd: Kreis, Dreieck, Quadrat",
            area="Volksgarten / Südpark",
            short="Formen sind überall – ihr sammelt Funde und macht daraus eine Mini‑Quest.",
            duration_minutes=45,
            distance_km=1.2,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Ruhiger Weg mit Schildern/Objekten.",
            route_steps=[
                "3 Formen wählen: Kreis, Quadrat/Rechteck, Dreieck (optional).",
                "Pro Form 2–3 Funde finden (Stehenbleiben‑Regel!).",
                "Mini‑Feier pro Fund („Gefunden!“).",
                "Abschluss: Carla malt eine Form mit dem Finger in Sand (wenn möglich).",
            ],
            preparation=["Dreieck ist optional – kann selten sein."],
            packing_list=["Wasser"],
            execution_tips=["Erst stehen, dann suchen.", "Wenn Dreieck fehlt: „seltenes Tier“ draus machen."],
            variations=["Nur 1 Form („Heute nur Kreise“)."],
            toddler_benefits=["Visuelle Wahrnehmung", "Kategorisieren", "Sprache"],
            carla_tip="„Ungefähr rund“ ist korrekt. Kein Korrigieren nötig.",
            risks=["Ablenkung beim Laufen"],
            mitigations=["Stehenbleiben‑Regel", "Ruhige Wege"],
            tags=["Lernen", "Ruhig", "Fokus"],
        ),

        # 17) Mini-Botaniker
        MicroAdventure(
            slug="mini-botaniker",
            title="Mini‑Botaniker: Pflanzen beobachten (ohne Pflücken)",
            area="Volksgarten",
            short="Texturen, Grüntöne, Mini‑Tierwelt – Forschen mit Respekt.",
            duration_minutes=50,
            distance_km=1.4,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Weg mit Wiese + Bäumen.",
            route_steps=[
                "Forscher‑Rolle: „Wir sind vorsichtig.“",
                "3 Texturen finden: glatt/rau/flauschig (wenn vorhanden).",
                "2 Grüntöne finden: hell/dunkel.",
                "Mini‑Tierwelt schauen: Ameise/Käfer – nur beobachten.",
                "Abschluss: „Danke, Wiese.“",
            ],
            preparation=["Grundregel: Nichts in den Mund, nichts pflücken."],
            packing_list=["Feuchttücher", "Wasser"],
            execution_tips=["Bei Unsicherheit: nur anschauen.", "Wenn Carla nicht stehen will: Aufgaben im Gehen."],
            variations=["Herbst: Samenstände/Blätterfarben", "Winter: Rinden‑Safari"],
            toddler_benefits=["Achtsamkeit", "Wortschatz", "Respekt/Empathie"],
            carla_tip="Regeln über Rolle: „Forscher sind vorsichtig“ statt „Nein!“.",
            risks=["Brennnessel/unbekannte Pflanzen", "Allergie/Pollen"],
            mitigations=["Nur bekannte Dinge anfassen", "Hände reinigen, kurz halten"],
            tags=["Natur", "Ruhig", "Lernen"],
        ),

        # 18) Wind-Orchester
        MicroAdventure(
            slug="wind-orchester",
            title="Wind‑Orchester: Bänder, Blätter, Geräusche",
            area="Südpark / Volksgarten",
            short="Ein Band macht Wind sichtbar – ihr werdet Musiker und Dirigentin.",
            duration_minutes=40,
            distance_km=1.0,
            best_time="windig",
            stroller_ok=True,
            start_point="Offene Wiese mit Abstand zu Menschen.",
            route_steps=[
                "Band/Tuch als Windfahne nutzen.",
                "10 Sekunden Wind hören: „Wind redet.“",
                "Orchester: schnell/langsam, laut/leise (Bewegungen).",
                "Windrennen: 15–20 Schritte, dann Pause.",
                "Abschluss: Verbeugen und einpacken.",
            ],
            preparation=["Bei Sturm: nicht machen."],
            packing_list=["Tuch/Band", "Wasser"],
            execution_tips=["Wind chill beachten: warm anziehen, kurz halten.", "Abstand zu anderen Kindern."],
            variations=["Wenn kein Wind: Schatten‑Jagd oder Geräusche‑Bingo."],
            toddler_benefits=["Koordination", "Impulskontrolle (Stop/Go)", "Sensorik"],
            carla_tip="Carla kann Dirigentin sein – du spielst mit.",
            risks=["Auskühlung", "Band ins Gesicht"],
            mitigations=["Schichten, kurze Dauer", "Kurzes weiches Band"],
            tags=["Bewegung", "Kreativ", "Wind"],
        ),

        # 19) Spuren-Suche
        MicroAdventure(
            slug="spuren-suche",
            title="Spuren‑Suche: Wer war hier?",
            area="Volksgarten / Südpark",
            short="Nach Regen wird der Park zum Krimi: Schuh‑, Reifen‑, Pfotenspuren finden.",
            duration_minutes=50,
            distance_km=1.5,
            best_time="nach Regen",
            stroller_ok=True,
            start_point="Weg mit sandigen/feuchten Stellen (nicht direkt im hohen Gras).",
            route_steps=[
                "Detektiv‑Story: „Wir lesen den Boden.“",
                "Spur 1: Mensch (Schuhprofil).",
                "Spur 2: Fahrzeug (Reifenlinie).",
                "Spur 3: Tier (Hund/Vogel – oder „unsichtbar“).",
                "Carla macht eigene Spur (Fuß in Sand).",
            ],
            preparation=["Nach Regen: rutschige Stellen einplanen."],
            packing_list=["Feuchttücher", "Wasser"],
            execution_tips=["Stehenbleiben zum Schauen.", "Tretminen scannen (Hundekot/Müll)."],
            variations=["Schnee‑Spuren im Winter", "Schatten‑Spuren bei Trockenheit"],
            toddler_benefits=["Beobachtung", "Vergleich", "Sprache & Hypothesen"],
            carla_tip="Wenn Carla „Dino!“ sagt: akzeptieren. Das ist Kleinkind‑Logik – und sie funktioniert.",
            risks=["Müll/Hundekot", "Rutschgefahr"],
            mitigations=["Nur Wege, du scannst zuerst", "Griffige Schuhe, Tempo runter"],
            tags=["Detektiv", "Lernen", "Natur"],
        ),

        # 20) Mini-Müllhelden
        MicroAdventure(
            slug="muell-helden",
            title="Mini‑Müllhelden: 10 Teile sammeln, Park retten",
            area="Volksgarten / Südpark",
            short="Kurze Action mit Wirkung: Carla spotten lassen, du sammelst sicher ein.",
            duration_minutes=35,
            distance_km=0.8,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Ruhiger Wegabschnitt mit Mülleimer in der Nähe.",
            route_steps=[
                "Rollen: Carla ist Spotter, du bist Sammler.",
                "Regeln: NIE Scherben, NIE Spritzen, NIE Kippen, NIE Flüssigkeiten.",
                "Mission: 10 sichere Teile finden (Papier/Folie).",
                "Entsorgen + Hände reinigen.",
                "Abschluss: High‑Five („Park gerettet“).",
            ],
            preparation=["Optional Handschuhe oder Greifer."],
            packing_list=["Mülltüte", "Handschuhe optional", "Feuchttücher"],
            execution_tips=["Kurz halten. Sicherheit > Menge.", "Bei gefährlichem Müll: nicht anfassen."],
            variations=["3‑Teile‑Mission (Mini‑Version)."],
            toddler_benefits=["Selbstwirksamkeit", "Regeln praktisch üben", "Teamwork"],
            carla_tip="Kein „Ih“. Frame positiv: „Wir helfen dem Park.“",
            risks=["Scherben/Nadeln (selten, aber ernst)", "Hygiene"],
            mitigations=["Carla fasst nichts an", "Nur sichere Teile, Hände reinigen"],
            tags=["Sozial", "Alltag", "Werte"],
        ),

        # 21) Dämmerungsrunde
        MicroAdventure(
            slug="abend-daemmerungsrunde",
            title="Dämmerungsrunde: Laternen & leise Schritte",
            area="Volksgarten / Nähe",
            short="Mini‑Abendabenteuer: Laternen zählen, leise gehen, sicher zurück.",
            duration_minutes=30,
            distance_km=0.9,
            best_time="dämmerung",
            stroller_ok=True,
            start_point="Beleuchteter Parkweg / ruhige Wohngegend am Park.",
            route_steps=[
                "Start‑Ritual: „Leise wie Katzen.“",
                "Bis zur 1. Laterne laufen, kurz stoppen, zählen.",
                "Mini‑Quest: hellste Laterne finden / 1 Stern suchen (optional).",
                "Bis zur 3. Laterne (oder vorher) – dann zurück.",
                "Abschluss: „Gute Nacht, Park.“",
            ],
            preparation=["Reflektor/helle Kleidung.", "Klare Wegstrecke vorher sagen."],
            packing_list=["Optional: kleine Taschenlampe", "Wasser (klein)"],
            execution_tips=["Nur beleuchtete, übersichtliche Wege.", "Kurz halten – Müdigkeit beachten."],
            variations=["Fenster‑Dämmerung: Laternen vom Fenster zählen (Indoor)."],
            toddler_benefits=["Mut im sicheren Rahmen", "Übergang Tag→Abend", "Rituale (schlafhilfreich)"],
            carla_tip="Wenn Carla Angst bekommt: Gefühl benennen, umdrehen, fertig. Kein Überreden.",
            risks=["Sichtbarkeit", "Abgelegene Bereiche", "Müdigkeit"],
            mitigations=["Beleuchtete Wege, Handkontakt", "Sehr kurze Dauer"],
            tags=["Achtsamkeit", "Ruhig", "Abend"],
        ),

        # 22) Wetter-Detektiv
        MicroAdventure(
            slug="wetter-detektiv",
            title="Wetter‑Detektiv: Wolken, Wind & Temperatur",
            area="Volksgarten / Südpark",
            short="Carla wird Wetterdetektivin: fühlen, schauen, vergleichen – und daraus eine Mini‑Wettervorhersage machen.",
            duration_minutes=35,
            distance_km=1.0,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Wiese + Bank (für Stopps) im Park.",
            route_steps=[
                "Mission: „Heute sammeln wir Wetter‑Hinweise.“",
                "Wind testen: Haare/Blätter beobachten (Band optional).",
                "Wolken schauen: weiß/grau, schnell/langsam (Wolkenrennen).",
                "Temperatur fühlen: Sonne vs. Schatten (kurz).",
                "Mini‑Report: Carla sagt „Heute ist …“ (kalt/warm/windig).",
            ],
            preparation=["Passende Kleidung wählen – das Abenteuer ist auch ein „Anzieh‑Lernmoment“."],
            packing_list=["Wasser", "Optional: kleines Band/Tuch"],
            execution_tips=["Kurze Stopps, nicht zu theoretisch.", "Wenn es regnet: Regen‑Orchester statt Report."],
            variations=["Indoor: Wetterreport am Fenster", "Profi: 3 Symbole malen (Wolke/Sonne/Wind)"],
            toddler_benefits=["Ursache/Wirkung", "Sprache (Wetterwörter)", "Achtsamkeit (beobachten statt hetzen)"],
            carla_tip="Keine Korrektur („falsch“). Du ergänzt: „Ja – und ich spüre auch Wind!“",
            risks=["Sonne/Hitze oder Kälte (je nach Tag)"],
            mitigations=["Dauer an Wetter anpassen, Wasser/Schichten"],
            tags=["Lernen", "Achtsamkeit", "Alltag"],
        ),

        # 23) Kreide-Wegekunst
        MicroAdventure(
            slug="kreide-wegekunst",
            title="Weg‑Kunst mit Kreide",
            area="Nähe / Parkwege",
            short="Kreide macht aus Asphalt eine Bühne – Spuren hinterlassen ohne Stress.",
            duration_minutes=45,
            distance_km=0.7,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Ruhiger Wegabschnitt (abseits Radverkehr).",
            route_steps=[
                "Atelier‑Zone festlegen (klein!).",
                "Mini‑Projekt: 10 Punkte malen und verbinden / 1 Straße zeichnen.",
                "Carla läuft die Linie ab (Bewegung!).",
                "Bonus: 1 Symbol gemeinsam (Herz/Kreis).",
                "Abschluss: Kreide einpacken, Hände reinigen.",
            ],
            preparation=["Feuchttücher für Kreidehände."],
            packing_list=["Kreide", "Feuchttücher", "Wasser"],
            execution_tips=["Nicht auf sensiblen Flächen (Denkmäler etc.).", "Nur im Stehen malen, nicht im Rennen."],
            variations=["Bei Nässe: Indoor‑Malen oder Punkte‑Version (kurz)."],
            toddler_benefits=["Feinmotorik", "Selbstwirksamkeit", "Kreativität ohne Leistungsdruck"],
            carla_tip="Wenn Carla nicht malen will: du malst, Carla läuft die Linie ab.",
            risks=["Kreidestaub im Auge", "Radweg‑Nähe"],
            mitigations=["Hände reinigen, nicht pusten", "Ruhige Stelle wählen"],
            tags=["Kreativ", "Ruhig", "Motorik"],
        ),

        # 24) Mini-Schatzkarte
        MicroAdventure(
            slug="mini-schatzkarte",
            title="Mini‑Schatzkarte: 3 Punkte zum Ziel",
            area="Volksgarten / Südpark",
            short="Start → Bank → Baum → Ziel: Karte als Quest‑Magie (ohne Aufwand).",
            duration_minutes=55,
            distance_km=1.6,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Startpunkt mit 2–3 Landmarken in der Nähe.",
            route_steps=[
                "Mini‑Karte malen (Strichmännchen‑Qualität reicht).",
                "3 Stationen nahe beieinander: Start → Punkt 1 → Punkt 2 → Ziel.",
                "Carla trägt die Karte (Navigatorin).",
                "An jeder Station: Mini‑Feier (Stempel/High‑Five).",
                "Schatz am Ziel: Snack oder Pause.",
            ],
            preparation=["Route klein halten (max. 3 Punkte)."],
            packing_list=["Zettel + Stift", "Wasser", "Optional: Snack"],
            execution_tips=["An Gabelungen stehen bleiben, dann entscheiden.", "Karte ist Symbol, kein Vertrag."],
            variations=["2‑Punkte‑Version", "Indoor‑Schatzkarte bei Regen"],
            toddler_benefits=["Sequenzdenken", "Orientierung an Landmarken", "Autonomie"],
            carla_tip="Wenn Carla unentschlossen ist: 3 Sekunden – dann wählst du.",
            risks=["Vorauslaufen an Kreuzungen/Gabelungen"],
            mitigations=["Handkontakt an Übergängen", "Ruhige Wege"],
            tags=["Detektiv", "Lernen", "Bewegung"],
        ),

        # 25) Stock-Trommeln
        MicroAdventure(
            slug="stoecke-trommeln",
            title="Stock‑Trommeln: Rhythmus im Park",
            area="Volksgarten / Südpark",
            short="Call‑and‑Response auf Baumstümpfen – laut sein, aber sicher und gemeinsam.",
            duration_minutes=35,
            distance_km=0.9,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Baumstumpf / ruhiger Bereich (nicht direkt neben ruhenden Menschen).",
            route_steps=[
                "2 kurze, stumpfe Stöcke finden.",
                "Regel: Stöcke bleiben unten (unter Hüfte).",
                "Du klopfst 3 Schläge – Carla antwortet.",
                "Tempo wechseln: langsam/schnell, leise/laut.",
                "Abschluss: Konzert‑Verbeugen, Stöcke zurücklegen.",
            ],
            preparation=["Abstand zu anderen Kindern/Menschen einplanen."],
            packing_list=["Feuchttücher"],
            execution_tips=["Wenn es zu wild wird: leise‑Modus oder Spielwechsel.", "Keine Stöcke in Gesichtshöhe."],
            variations=["Indoor: Kissen‑Trommeln", "Wind‑Orchester statt Trommeln"],
            toddler_benefits=["Rhythmus & Timing", "Impulskontrolle", "Turn‑Taking"],
            carla_tip="Carla kann Dirigentin sein – du trommelst.",
            risks=["Stock im Gesicht", "Aggressives Hauen"],
            mitigations=["Kurze Stöcke, klare Regel", "Bei „Hauen“ sofort Wechsel"],
            tags=["Kreativ", "Musik", "Bewegung"],
        ),

        # 26) Mini-Bootrennen
        MicroAdventure(
            slug="mini-bootrennen",
            title="Mini‑Bootrennen mit Blättern",
            area="Volksgarten / Südpark",
            short="Blätter als Boote – Wasserwege beobachten (mit Abstand, sicher!).",
            duration_minutes=40,
            distance_km=1.0,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Sicherer Wasser‑Spot mit stabilem Stand und Abstand.",
            route_steps=[
                "2–3 große Blätter vom Boden finden (nicht pflücken).",
                "Startlinie festlegen (mit Abstand zum Wasser).",
                "Blätter loslassen, beobachten, anfeuern.",
                "Wenn’s hängen bleibt: Story („Boot hat Pause“).",
                "Abschluss: Blätter zurück, Hände reinigen.",
            ],
            preparation=["Wasser‑Regel klar: Carla bleibt bei dir."],
            packing_list=["Feuchttücher", "Wasser"],
            execution_tips=["Kein Rennen am Wasser.", "Rutschige Stellen meiden."],
            variations=["Bei Rutschgefahr: Enten‑Zählerei statt Bootrennen."],
            toddler_benefits=["Geduld & Beobachtung", "Ursache/Wirkung", "Sprache (schnell/langsam)"],
            carla_tip="Wenn Carla näher will: „Boote fahren ohne uns“ + neue Blätter suchen.",
            risks=["Ausrutschen/Ufer", "Schmutzwasser/Hygiene"],
            mitigations=["Abstand halten, griffige Stelle", "Hände reinigen"],
            tags=["Natur", "Ruhig", "Wasser"],
        ),

        # 27) Mini-Geschenke für Bäume
        MicroAdventure(
            slug="mini-geschenke-fuer-baeume",
            title="Mini‑Geschenke für Bäume: Natur‑Kunst ohne Pflücken",
            area="Volksgarten",
            short="Bodenfunde als Kranz/Spirale am Baumfuß – Dankbarkeit + Kreativität.",
            duration_minutes=30,
            distance_km=0.6,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Ruhiger Baum am Weg (nicht in Beeten).",
            route_steps=[
                "„Freundebaum“ auswählen: Carla entscheidet.",
                "Nur Bodenfunde sammeln (Blätter, kleine Stöcke, Steine – groß genug).",
                "Am Baumfuß eine Spirale oder einen Kranz legen.",
                "Mini‑Ritual: „Danke, Baum“ (oder winken).",
                "Alles so lassen, dass niemand stolpert – dann weiter.",
            ],
            preparation=["Bei Mundphase: nur große Blätter/Äste, keine Kleinteile."],
            packing_list=["Feuchttücher", "Wasser"],
            execution_tips=["Nicht an Pflanzen reißen.", "Klein halten – 10 Minuten Kunst reichen."],
            variations=["Herbst: Blätterfarben‑Kranz", "Winter: Stöcke‑Stern (kurz)"],
            toddler_benefits=["Empathie/Respekt", "Feinmotorik", "Symbolisches Denken"],
            carla_tip="Wenn Carla zerstört/umsortiert: „Neue Version!“ – das ist der Prozess.",
            risks=["Kleinteile im Mund", "Schmutzige Hände"],
            mitigations=["Große Funde", "Hände reinigen"],
            tags=["Kreativ", "Ruhig", "Natur"],
        ),

        # 28) Morgentau-Expedition
        MicroAdventure(
            slug="morgentau-expedition",
            title="Morgentau‑Expedition",
            area="Volksgarten",
            short="Früh raus: Glitzer‑Gras, leise Welt und kurze Mini‑Missionen.",
            duration_minutes=35,
            distance_km=1.0,
            best_time="frühmorgens",
            stroller_ok=True,
            start_point="Wiese/Grasrand im Volksgarten (abseits Radweg).",
            route_steps=[
                "Mission: „Wo glitzert es am meisten?“",
                "Tautropfen zählen (eins, zwei, viele).",
                "Sonne/Schatten vergleichen (kurz).",
                "2 kurze Laufstücke, damit Carla warm bleibt.",
                "Abschluss: „Tautropfen‑Tschüss“ und zurück.",
            ],
            preparation=["Wasserdichte Schuhe oder Ersatzsocken empfehlenswert."],
            packing_list=["Wasser", "Feuchttücher", "Optional: Ersatzsocken"],
            execution_tips=["Kurz halten – Morgentau ist kalt.", "Auf rutschigen Wegen vorsichtig."],
            variations=["Mit Lupe beobachten (optional)."],
            toddler_benefits=["Sensorik", "Achtsamkeit", "Ruhiger Start in den Tag"],
            carla_tip="Wenn Carla müde ist: nur 1 Glitzer‑Spot, dann Ende.",
            risks=["Nasse Füße → Auskühlung", "Rutschige Stellen"],
            mitigations=["Kurze Dauer, warm anziehen", "Griffige Wege"],
            tags=["Achtsamkeit", "Ruhig", "Natur"],
        ),

        # 29) Regen-Orchester
        MicroAdventure(
            slug="regen-orchester",
            title="Regen‑Orchester unter Bäumen",
            area="Südpark / Volksgarten",
            short="Regen klingt überall anders – ihr hört, vergleicht und klatscht den Rhythmus.",
            duration_minutes=30,
            distance_km=0.7,
            best_time="bei Regen",
            stroller_ok=True,
            start_point="Unter großen Bäumen (nicht bei Sturm).",
            route_steps=[
                "10–20 Sekunden nur hören.",
                "Regen auf Blättern vs. Boden vergleichen.",
                "Rhythmus klatschen oder stampfen (leise).",
                "Kurze Bewegungsschleife gegen Auskühlung.",
                "Abschluss: Orchester‑Verbeugen.",
            ],
            preparation=["Regenkleidung.", "Bei Gewitter: abbrechen."],
            packing_list=["Regenjacke", "Optional: Regenschirm", "Wasser"],
            execution_tips=["Kurz halten, warm bleiben.", "Bei glatten Wegen kein Rennen."],
            variations=["Indoor: Regen am Fenster hören + beschreiben."],
            toddler_benefits=["Auditive Wahrnehmung", "Impulskontrolle", "Flexibilität bei „schlechtem Wetter“"],
            carla_tip="Nenn den Regen einen Trommler – Story macht’s leichter.",
            risks=["Auskühlung", "Rutschgefahr", "Gewitter"],
            mitigations=["Kurze Dauer, Schichten", "Ruhige, griffige Wege", "Bei Gewitter sofort rein"],
            tags=["Regen", "Achtsamkeit", "Musik"],
        ),

        # 30) Impro-Drachen mit Tuch
        MicroAdventure(
            slug="drachen-impro",
            title="Impro‑Drachen mit Tuch",
            area="Volksgarten",
            short="Wind sichtbar machen: Ein Tuch wird zum Drachen, Carla zur Dirigentin.",
            duration_minutes=40,
            distance_km=1.2,
            best_time="windig",
            stroller_ok=True,
            start_point="Offene Wiese mit Abstand zu Menschen.",
            route_steps=[
                "Wind finden: Tuch hochhalten, Bewegung beobachten.",
                "Drachenflug: langsam laufen → Tuch steigt, schneller → tanzt.",
                "Windrennen: 15–20 Schritte, dann Pause.",
                "Drachen schlafen legen (Tuch zusammenfalten).",
            ],
            preparation=["Kein Sturm – nur moderater Wind."],
            packing_list=["Tuch/Band", "Wasser"],
            execution_tips=["Abstand halten, keine Stöcke nötig.", "Bei Nässe kein Sprint."],
            variations=["Wenn kein Wind: Schatten‑Jagd oder Formen‑Schnitzeljagd."],
            toddler_benefits=["Grobmotorik", "Tempo dosieren", "Kausalität (Wind/Tempo → Bewegung)"],
            carla_tip="Carla darf bestimmen: schnell/langsam. Kontrolle senkt Widerstand.",
            risks=["Auskühlung (Windchill)", "Stolpern beim Rennen"],
            mitigations=["Schichten, kurze Dauer", "Nur sichere Laufstrecken"],
            tags=["Bewegung", "Wind", "Spaß"],
        ),

        # 31) Schatten-Theater
        MicroAdventure(
            slug="schatten-theater",
            title="Schatten‑Theater",
            area="Volksgarten / Südpark",
            short="Hände werden Tiere, Schatten werden Story – Theater ohne Bühne.",
            duration_minutes=40,
            distance_km=1.0,
            best_time="sonnig",
            stroller_ok=True,
            start_point="Heller Boden / Fläche mit klaren Schatten.",
            route_steps=[
                "Bühne suchen (hell, sicher, abseits Radweg).",
                "2–3 Figuren machen (Vogel, Monsterkralle).",
                "Mini‑Story in 3 Akten: Start – Problem – Lösung.",
                "Carla bestimmt Rollen, du spielst mit.",
                "Abschluss: „Vorhang zu“ + Verbeugen.",
            ],
            preparation=["Sonnencreme/Cap bei starker Sonne."],
            packing_list=["Wasser"],
            execution_tips=["Kurz halten, nicht in praller Sonne überziehen.", "Wenn bewölkt: Figuren‑Theater ohne Schatten."],
            variations=["Indoor: Lampe + Wand (zu Hause)."],
            toddler_benefits=["Sprache & Erzählstruktur", "Symbolisches Denken", "Gemeinsame Aufmerksamkeit"],
            carla_tip="Wenn Carla nicht will: 1 Figur + 1 Gag reicht oft.",
            risks=["Sonne/Hitze", "Im Weg stehen (Radweg)"],
            mitigations=["Schattenpausen, Wasser", "Ruhige Stelle wählen"],
            tags=["Kreativ", "Ruhig", "Sprache"],
        ),

        # 32) Baumstamm-Parcours
        MicroAdventure(
            slug="baumstamm-parcours",
            title="Baumstamm‑Parcours",
            area="Volksgarten / Südpark",
            short="Klettern in sicherer Dosis: niedrige Stämme, kleine Levels, klare Regeln.",
            duration_minutes=45,
            distance_km=1.2,
            best_time="nachmittags",
            stroller_ok=False,
            start_point="Niedrige, stabile Baumstämme/Begrenzungen (trocken, griffig).",
            route_steps=[
                "Regel: nur so hoch, dass du jederzeit halten kannst.",
                "Level 1: draufsteigen + 3–6 Schritte gehen.",
                "Level 2: Stamm → Boden → Stamm (kleine Übergänge).",
                "Superhelden‑Stopp: auf Kommando stehen bleiben.",
                "Abschluss: Siegerpose + runter (fertig ist fertig).",
            ],
            preparation=["Nur bei trockenem, nicht glattem Holz."],
            packing_list=["Pflaster (optional)", "Wasser"],
            execution_tips=["Bei Nässe auslassen.", "Grenze: mehr Wiederholung statt mehr Höhe."],
            variations=["Boden‑Lava‑Spiel ohne Klettern (wenn zu glatt)."],
            toddler_benefits=["Gleichgewicht", "Motorisches Planen", "Mut + Risikokompetenz"],
            carla_tip="Wenn Carla „noch höher“ will: „Heute nur die niedrigen Drachen“ + Alternative anbieten.",
            risks=["Sturz", "Splitter/raue Stellen"],
            mitigations=["Niedrige Elemente, Griffnähe", "Oberfläche prüfen, ggf. wechseln"],
            tags=["Bewegung", "Motorik", "Abenteuer"],
        ),

        # 33) Käfer-Detektive (aus Seed‑V2)
        MicroAdventure(
            slug="kaefer-detektive",
            title="Käfer‑Detektive: Mini‑Safari am Wiesenrand",
            area="Volksgarten",
            short="Mit Forscherblick: kleine Krabbler finden, beobachten, beschreiben.",
            duration_minutes=50,
            distance_km=1.2,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Wiesenrand an einem ruhigen Weg (nicht im hohen Gras starten).",
            route_steps=[
                "Forscher‑Regel: Wir gucken mit Augen, nicht mit Mund – und lassen Tiere in Ruhe.",
                "Mission 1: Finde 1 Ameise oder Käfer (auch kurz zählt).",
                "Mission 2: Beobachte 10 Sekunden: läuft, krabbelt, fliegt?",
                "Mission 3: „Käfer‑Interview“: Du fragst, Carla antwortet (fantasieren erlaubt).",
                "Abschluss: Hände reinigen + „Danke, kleine Tiere“.",
            ],
            preparation=[
                "Optional eine kleine Lupe einpacken (geht auch ohne).",
                "Wenn Carla gerade viel „Mund‑Phase“ hat: eher schauen als sammeln.",
            ],
            packing_list=["Feuchttücher / Handreinigung", "Wasser + kleiner Snack", "Optional: Lupe"],
            execution_tips=[
                "Kleinkind‑Tempo: lieber 3 Mini‑Funde als 1 Stunde Suche.",
                "Wenn nichts zu sehen ist: „Unsichtbarer Käfer‑Tag“ – dann Geräusche oder Spuren‑Suche.",
            ],
            variations=["Regen‑Variante: Regen‑Orchester oder Spuren‑Suche auf nassem Boden.", "Profi: Käfer‑Farben suchen (schwarz, braun, rot)."],
            toddler_benefits=["Aufmerksamkeit & Fokus", "Sprache: beschreiben/benennen", "Respekt vor Lebewesen"],
            carla_tip="Wenn Carla anfassen will: Alternative geben – „Zeig ganz nah dran, ohne zu berühren.“",
            risks=["Insektenstich (selten)", "Schmutzige Hände → Hände im Gesicht"],
            mitigations=["Nicht im hohen Gras wühlen, Abstand halten", "Hände reinigen"],
            tags=["Natur", "Lernen", "Detektiv", "Ruhig"],
        ),

        # 34) Sonnenblumen-Zählung (aus Seed‑V2)
        MicroAdventure(
            slug="sonnenblumen-zaehlung",
            title="Gelb‑Mission: Sonnenblumen zählen (oder gelbe Blüten)",
            area="Südpark / Volksgarten",
            short="Zählen, vergleichen, suchen: gelbe Blüten werden zur Mini‑Mathe‑Quest.",
            duration_minutes=45,
            distance_km=1.4,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Nähe eines Beets oder Wiesenbereichs mit Blüten (wenn vorhanden).",
            route_steps=[
                "Mission: Heute suchen wir GELB.",
                "Finde 5 gelbe Dinge (Blüten, Schilder, Jacken – alles zählt).",
                "Zählen: Wie viele gelbe Blüten siehst du? (eins, zwei, viele).",
                "Vergleich: Welche ist größer/kleiner?",
                "Abschluss: 1 gelbe Sache fotografieren oder zeichnen (optional).",
            ],
            preparation=["Kein Pflücken: nur schauen.", "Bei Pollenempfindlichkeit: kurz halten."],
            packing_list=["Wasser", "Feuchttücher", "Optional: Handy für 1 Foto"],
            execution_tips=["Zahlen sind Bonus – „Zeig mir Gelb“ reicht.", "Wenn keine Blüten da sind: gelbe Objekte/Schilder nutzen."],
            variations=["Profi: Gelb + Kreis kombinieren.", "Regen: Indoor‑Gelb‑Suche."],
            toddler_benefits=["Frühe Mathe‑Intuition (mehr/weniger)", "Visuelle Suche", "Sprache (Farben)"],
            carla_tip="Nicht korrigieren: „Ich sehe auch viele – lass uns zusammen schauen.“",
            risks=["Allergie/Pollen (je nach Saison)"],
            mitigations=["Kurz halten, Hände reinigen, Distanz zu Blüten"],
            tags=["Lernen", "Ruhig", "Natur"],
        ),

        # 35) Frost-Spaziergang (aus Seed‑V2)
        MicroAdventure(
            slug="frost-spaziergang",
            title="Frost‑Spaziergang: Knirschen, Atemwolken, Eis‑Glitzer",
            area="Volksgarten",
            short="Winter‑Quest: knirschenden Boden hören, Atemwolken sehen – kurz, warm, sicher.",
            duration_minutes=30,
            distance_km=0.9,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Beleuchteter, griffiger Weg im Park (keine glatten Platten).",
            route_steps=[
                "Warm‑up: Atemwolken machen („Drachenatem“).",
                "Mission 1: 3 knirschende Stellen finden (Kies/Blätter/Schnee).",
                "Mission 2: Eis‑Glitzer suchen (Reif am Grasrand – nur schauen).",
                "2 kurze Laufstücke, damit Carla warm bleibt.",
                "Abschluss: Wärme‑Bank kurz oder direkt nach Hause.",
            ],
            preparation=["Schichten: warm + winddicht, Mütze/Handschuhe.", "Dauer bewusst kurz planen."],
            packing_list=["Mütze/Handschuhe", "Optional: warmes Getränk", "Optional: Ersatzhandschuhe"],
            execution_tips=["Kein Klettern/Balancieren bei Glätte.", "Wechsel: schauen → laufen → schauen."],
            variations=["Schnee: Fußspuren zählen.", "Ohne Frost: Dämmerungsrunde."],
            toddler_benefits=["Körperwahrnehmung", "Achtsamkeit (Geräusche/Luft)", "Winter‑Mut"],
            carla_tip="Erst Gefühl benennen („du frierst“), dann Lösung (kurz rennen).",
            risks=["Ausrutschen", "Auskühlung"],
            mitigations=["Griffige Wege, Tempo runter", "Kurz halten, warm anziehen"],
            tags=["Winter", "Ruhig", "Achtsamkeit"],
        ),

        # 36) Mini-Kompass-Abenteuer (aus Seed‑V2)
        MicroAdventure(
            slug="mini-kompass-abenteuer",
            title="Mini‑Kompass‑Abenteuer: Links, rechts, geradeaus!",
            area="Volksgarten / Südpark",
            short="Orientierung als Spiel: Carla entscheidet an Weggabelungen, ihr schafft Etappen.",
            duration_minutes=55,
            distance_km=1.8,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Rundweg mit 2–3 klaren Weggabelungen.",
            route_steps=[
                "Carla ist Navigatorin – Entscheidungen im Stehen treffen.",
                "Weggabelung 1: links/rechts wählen (du bestätigst).",
                "Etappe: 60–100 Schritte bis zur nächsten Marke (Bank/Baum).",
                "Weggabelung 2: wieder wählen; Weg bekommt Quest‑Namen.",
                "Abschluss: zu klar definiertem Ziel (Start/Bank/Spielplatz).",
            ],
            preparation=["Endpunkt vorher festlegen, damit es nicht endlos wird."],
            packing_list=["Wasser + Snack", "Optional: Zettel + Stift (Mini‑Map)"],
            execution_tips=["Links/rechts nicht erzwingen – Entscheidungsspiel reicht.", "Wenn Carla alles will: zwei Optionen anbieten."],
            variations=["Indoor‑Version mit 2 Abzweigungen.", "Profi: „Immer zur Sonne“ (nur Story)."],
            toddler_benefits=["Selbstwirksamkeit (Entscheiden)", "Sequenzdenken", "Richtungsbegriffe"],
            carla_tip="Wenn Carla nicht wählen kann: 3 Sekunden, dann wählst du – Druck rausnehmen.",
            risks=["Spontanes Abbiegen nahe Radwegen"],
            mitigations=["An Gabelungen stoppen + Handkontakt", "Ruhige Wege"],
            tags=["Lernen", "Bewegung", "Detektiv"],
        ),

        # 37) Natur-Farblabor (aus Seed‑V2)
        MicroAdventure(
            slug="natur-farblabor",
            title="Natur‑Farblabor: Palette sammeln wie ein Künstler",
            area="Volksgarten",
            short="Bodenfunde als Farbpalette: hell → dunkel sortieren – ruhig, kreativ, sehr kleinkindfreundlich.",
            duration_minutes=55,
            distance_km=1.3,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Wegabschnitt mit Wiese + Bäumen.",
            route_steps=[
                "Regel: Nur Bodenfunde, nichts abreißen.",
                "5 Grüntöne (oder hell/dunkel) finden.",
                "2 Brauntöne (Erde/Rinde/trockene Blätter) finden.",
                "Palette legen: hell → dunkel sortieren.",
                "Abschluss: Foto optional, alles zurückgeben.",
            ],
            preparation=["Optional: kleines Tuch als Atelier.", "Bei Mundphase: nur große Blätter."],
            packing_list=["Optional: kleines Tuch", "Feuchttücher", "Wasser"],
            execution_tips=["Für 2,5: hell/dunkel reicht.", "Jede Wahl feiern – keine falschen Farben."],
            variations=["Herbst: Rot/Orange‑Palette", "Indoor‑Palette mit Haushaltsobjekten"],
            toddler_benefits=["Sortieren & visuelle Wahrnehmung", "Feinmotorik", "Kreativität"],
            carla_tip="Umsortieren ist Lernen: „Neue Version!“",
            risks=["Kleinteile im Mund", "Schmutzige Hände"],
            mitigations=["Große Funde, bei Mundphase nur schauen", "Hände reinigen"],
            tags=["Kreativ", "Ruhig", "Natur"],
        ),

        # 38) Hunde-Beobachtungsrunde (aus Seed‑V2)
        MicroAdventure(
            slug="hunde-beobachtungsrunde",
            title="Hunde‑Beobachtungsrunde: Respekt‑Training mit Abstand",
            area="Volksgarten / Südpark",
            short="Hunde anschauen, beschreiben, Regeln lernen: fragen, Abstand, Hände sauber.",
            duration_minutes=45,
            distance_km=1.2,
            best_time="vormittags",
            stroller_ok=True,
            start_point="Weg, auf dem regelmäßig Hunde vorbeikommen (ohne Gedränge).",
            route_steps=[
                "Regel: Hunde erst aus Distanz anschauen – anfassen nur nach Erlaubnis.",
                "3 Hunde beobachten: groß/klein, schnell/langsam.",
                "„Hund spricht“: Carla erfindet Gedanken (Story statt Nähe).",
                "Optional 1 kurzer Kontakt, wenn Besitzer zustimmt und Hund ruhig ist.",
                "Abschluss: Hände reinigen + „Danke, Hunde“.",
            ],
            preparation=["Carla‑Regel üben: Stop‑Hand + „Darf ich streicheln?“"],
            packing_list=["Feuchttücher", "Wasser", "Optional: Snack (Übergang nach Kontakt)"],
            execution_tips=["Carla darf nie hinrennen.", "Ein Hund reicht – sonst wird’s zu viel."],
            variations=["Regen: Pfotenabdrücke als Spuren‑Suche.", "Indoor: Hundebuch + Geräusche."],
            toddler_benefits=["Sozialregeln & Empathie", "Impulskontrolle", "Sprache (beschreiben)"],
            carla_tip="Wenn Carla losstürmt: ruhig blocken + „Stopp. Fragen.“ (kein Schimpfen).",
            risks=["Hund erschrickt → Anspringen/Biss (selten)", "Hygiene"],
            mitigations=["Nur mit Erlaubnis + ruhige Hunde, Abstand halten", "Hände reinigen"],
            tags=["Tiere", "Sozial", "Lernen"],
        ),

        # 39) Park-Geschichten-Bank (aus Seed‑V2)
        MicroAdventure(
            slug="park-geschichten-bank",
            title="Park‑Geschichten‑Bank: 5 Minuten Fantasie, 1 große Story",
            area="Volksgarten",
            short="Eine Bank wird zur Bühne: ihr erfindet zusammen eine Mini‑Geschichte in 3 Akten.",
            duration_minutes=40,
            distance_km=1.0,
            best_time="nachmittags",
            stroller_ok=True,
            start_point="Ruhige Bank mit Blick auf Wiese/Weg (nicht am Radweg).",
            route_steps=[
                "„Das ist unsere Geschichten‑Bank.“",
                "Akt 1: Hauptfigur wählen (Carla entscheidet).",
                "Akt 2: Problem (z. B. Vogel sucht Hut).",
                "Akt 3: Lösung (Carla entscheidet) + Happy End.",
                "Optional: Blatt/Stock als Requisit (nur Bodenfunde).",
            ],
            preparation=["Wenn Carla nicht sitzen will: Story im Gehen erzählen (Bank nur Start)."],
            packing_list=["Wasser", "Optional: Notizbuch (1 Satz festhalten)"],
            execution_tips=["Ping‑Pong‑Sätze halten Tempo.", "Frage: „Und dann?“ statt „Warum?“"],
            variations=["Abend: Laternen‑Story", "Regen: Indoor am Fenster"],
            toddler_benefits=["Sprache & Narratives Denken", "Bindung (gemeinsamer Fokus)", "Emotionen spielerisch verarbeiten"],
            carla_tip="Wenn Carla nur Quatsch sagt: übertreiben und mitgehen – Humor ist Kooperation.",
            risks=["Zu lange sitzen → Unruhe", "Bank am Radweg"],
            mitigations=["5–10 Minuten Story, dann weiter", "Ruhige Bank wählen"],
            tags=["Kreativ", "Ruhig", "Sprache"],
        ),
    ]

    # Apply V2 metadata centrally (before validate) so UI/LLM always gets consistent parameters.
    _apply_v2_classification(adventures)

    # Validate + unique slug guard
    for a in adventures:
        a.validate()
    ensure_unique_slugs(adventures)

    return adventures
